console.log('1: about to import hono');
import { Hono } from 'hono';
console.log('2: hono imported');
import { serve } from '@hono/node-server';
console.log('3: serve imported');
import { trpcServer } from '@hono/trpc-server';
console.log('4: trpc imported');
import { appRouter } from './src/api/router.js';
console.log('5: router imported');
import { initDb } from './src/db/schema.js';
console.log('6: schema imported');
import { runMigrations } from './src/db/migrations.js';
console.log('7: migrations imported');
import { reloadProviderStats } from './src/lib/selfLearning.js';
console.log('8: selfLearning imported');
import { addSSEClient, removeSSEClient } from './src/lib/sse.js';
console.log('9: sse imported');
import { checkRateLimit } from './src/lib/rateLimiter.js';
console.log('10: rateLimiter imported');
import { getCacheStats } from './src/lib/cache.js';
console.log('11: cache imported');
import { getSchedulerStatus, stopScheduler } from './src/lib/scheduler.js';
console.log('12: scheduler imported');
import { getWebhookStatus } from './src/lib/webhooks.js';
console.log('13: webhooks imported');
import { getSelfLearningStats } from './src/lib/selfLearning.js';
console.log('14: learning stats imported');
import { closeBrowser } from './src/lib/browserService.js';
console.log('15: browserService imported');
console.log('ALL IMPORTS OK');
